# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0333f6e9e79c8f84b0b00fbfac7ab9c4410e63bd9c8f27e8c5060090fa0a7e1f21ea81b47436691cd6e84fb2e1c06676a83871c72296c84fb968fe6992900b24

test:
  secret_key_base: 20c629131dc05db534718436f659a525d2912416bdadf19705bbb66a1f67fad65365bf3eaf8a4c0a6b6e1304a44716b1cc8376877876c01a44787a99fc4db8dd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
